### ISSUE TITLE
error executing?

### ISSUE THREAD

**Issue by Rhandyx** [avilum/smart-url-fuzzer#7]
`# python -V
Python 2.7.17
`

`/smart-url-fuzzer#  python fuzz.py -u https://www.facebook.com -l words_lists/list-php.txt
Traceback (most recent call last):
  File "fuzz.py", line 8, in <module>
    import requests
ImportError: No module named requests`

**Comment by avilum** [comment]
Hey,
Please install the requirements;
`python -m pip install -r requirements.txt`
